name: Deploy Lambda Function

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::200110254415:role/proyect-user
          aws-region: us-east-1

      - name: Install dependencies and package Lambda
        run: |
          pip install -r requirements.txt -t package
          cp lambda_function.py package/
          cd package && zip -r ../function.zip .

      - name: Upload ZIP to S3
        run: |
         BUCKET_NAME=s3-data-entrada-covid-brayner573
         BRANCH=${GITHUB_REF##*/}
         TIMESTAMP=$(date +%Y%m%d-%H%M%S)
         ZIP_KEY=lambda/function-${TIMESTAMP}.zip
         aws s3 cp function.zip s3://$BUCKET_NAME/$ZIP_KEY
         echo "ZIP_KEY=$ZIP_KEY" >> $GITHUB_ENV  
      - name: Deploy Lambda function from S3
        run: |
         FUNCTION_NAME=lambda_transformador_20_reglas
         aws lambda update-function-code \
         --function-name $FUNCTION_NAME \
         --s3-bucket s3-data-entrada-covid-brayner573 \
         --s3-key $ZIP_KEY      